---

- name: Set hostname
  hosts: pis
  become: yes

  tasks:
    - name: Set hostname as defined in inventory
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Setup hosts file
      template:
        src: hosts
        dest: /etc/hosts
    - name: Restart Avahi daemon # so that DNS server gets new hostname
      service:
        name: avahi-daemon
        state: restarted
