---

- name: Download k8s-on-rpi
  get_url:
    url: "{{ k8s.archive_url }}"
    dest: "./{{ k8s.destination_filename }}"

- name: Install tools
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ k8s.tools }}"

- name: Install Kubernetes
  include: install-kubernetes-using-kubeadm.yml
