---

- name: Download k8s-on-rpi
  get_url:
    url: "{{ k8s.archive_url }}"
    dest: "./{{ k8s.destination_filename }}"

- name: Install tools
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ k8s.tools }}"

- name: Unzip the k8s-on-rpi archive
  unarchive:
    src: "{{ k8s.destination_filename }}"
    dest: "./"
    copy: no
  tags:
    - unzip

- name: Install Kubernetes master
  command: "./k8s-on-rpi-master/install-k8s-master.sh"
  tags:
    - install

- name: Check docker-bootstrap.service is running
  include: check-service.yml
  vars:
    service_name: "{{ item }}"
  with_items:
    - "docker-bootstrap.service"
    - "k8s-etcd.service"
    - "k8s-flannel.service"
    - "docker.service"
    - "k8s-master.service"
  tags: check
