---

- name: Download k8s-on-rpi
  get_url:
    url: "{{ k8s.archive_url }}"
    dest: "./{{ k8s.destination_filename }}"

- name: Install tools
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ k8s.tools }}"

- name: Unzip the k8s-on-rpi archive
  unarchive:
    src: "{{ k8s.destination_filename }}"
    dest: "./"
    remote_src: yes

- name: Install Kubernetes master
  command: "./k8s-on-rpi-master/install-k8s-master.sh"

# TODO: Add checks/validations that things are up and running
