---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install tools
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - bridge-utils

- name: Install Kubernetes
  include: install-kubernetes-using-kubeadm.yml
