---

- name: Install tools
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - bridge-utils

- name: Install Kubernetes
  include: install-kubernetes-using-kubeadm.yml
