---

- name: Reset k8s master
  shell: "kubeadm reset"
  register: kubeadm_reset_result

- name: Output result
  debug:
    var: kubeadm_reset_result

- name: Init k8s master
  shell: "kubeadm init --pod-network-cidr {{ flannel_network_cidr }}"
  register: kubeadm_init_result

- name: Output result
  debug:
    var: kubeadm_init_result

- shell: cp /etc/kubernetes/admin.conf $HOME/
  become: yes
  tags:
    - post-init

- shell: chown $(id -u):$(id -g) $HOME/admin.conf
  become: yes
  tags:
    - post-init

# TODO: noop... remove
- shell: export KUBECONFIG=$HOME/admin.conf
  become: yes
  tags:
    - post-init
    - flannel

- name: Copy flannel config
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  become: yes
  with_items:
    - kube-flannel.yml
    - kube-flannel-rbac.yml
  tags:
    - flannel

- name: Apply Flannel configs
  shell: "kubectl apply -f {{ item }} --kubeconfig $HOME/admin.conf"
  become: yes
  with_items:
    - /tmp/kube-flannel.yml
    - /tmp/kube-flannel-rbac.yml
  tags:
    - flannel

- name: Get pods
  shell: kubectl get pods --all-namespaces --kubeconfig $HOME/admin.conf
  become: yes
  register: pods_result
  tags:
    - flannel

- debug:
    var: pods_result
  tags:
    - flannel
