apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: busybox-demo
        image: hypriot/rpi-busybox-httpd
        ports:
        - containerPort: 9999
