---

- name: Check if Docker is already installed
  command: docker ps
  become: yes
  ignore_errors: yes
  changed_when: False
  register: docker_ps_result

- name: Install Docker if needed
  shell: curl -sSL https://get.docker.com | sh
  when: docker_ps_result.rc != 0

- name: Install needed packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip

- name: Install pip modules
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
